configurations:
  - sources:
      - SDK/Sources/Dependencies
    templates:
      - SourceryTemplates/AutoMockable.stencil
    output: SDK/Sources/Dependencies/Sourcery
    args:
      hideVersionHeader: true
      autoMockableImports:
        - Combine
        - SwiftUI
        - Core

  - sources:
      - SDK/Sources/InspectionFeature
    templates:
      - SourceryTemplates/Scoped.stencil
    output: SDK/Sources/InspectionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/RecognitionFeature
    templates:
      - SourceryTemplates/Scoped.stencil
    output: SDK/Sources/RecognitionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/SelectionFeature
    templates:
      - SourceryTemplates/Scoped.stencil
    output: SDK/Sources/SelectionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/RootFeature
    templates:
      - SourceryTemplates/Scoped.stencil
    output: SDK/Sources/RootFeature/Sourcery
    args:
      hideVersionHeader: true
