configurations:
  - sources:
      - SDK/Sources/Services
    templates:
      - SourceryTemplates/AutoMockable.stencil
    output: SDK/Sources/Services/Sourcery
    args:
      hideVersionHeader: true
      autoMockableImports:
        - Combine
        - SwiftUI
        - Models

  - sources:
      - SDK/Sources/Persistence
    templates:
      - SourceryTemplates/AutoMockable.stencil
    output: SDK/Sources/Persistence/Sourcery
    args:
      hideVersionHeader: true
      autoMockableImports:
        - Models

  - sources:
      - SDK/Sources/Repositories
    templates:
      - SourceryTemplates/AutoMockable.stencil
    output: SDK/Sources/Repositories/Sourcery
    args:
      hideVersionHeader: true
      autoMockableImports:
        - Models

  - sources:
      - SDK/Sources/InspectionFeature
    templates:
      - SourceryTemplates/Child.stencil
    output: SDK/Sources/InspectionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/RecognitionFeature
    templates:
      - SourceryTemplates/Child.stencil
    output: SDK/Sources/RecognitionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/SelectionFeature
    templates:
      - SourceryTemplates/Child.stencil
    output: SDK/Sources/SelectionFeature/Sourcery
    args:
      hideVersionHeader: true

  - sources:
      - SDK/Sources/RootFeature
    templates:
      - SourceryTemplates/Child.stencil
    output: SDK/Sources/RootFeature/Sourcery
    args:
      hideVersionHeader: true
