configurations:
    - sources:
        - SDK/Sources/Dependencies
      templates:
        - SourceryTemplates/AutoMockable.stencil
      output: SDK/Sources/Dependencies/Sourcery
      args:
        hideVersionHeader: true
        autoMockableImports:
          - Combine
          - SwiftUI
          - Core
