excluded: # Paths to ignore during linting. Takes precedence over `included`.
  - SDK/Sources/*/Sourcery/*.generated.swift
  - SDK/Sources/*/SwiftGen/*.generated.swift
  - SDK/Sources/KSSDiff
  - SDK/Sources/CasePaths
  - SDK/Sources/Clocks
  - SDK/Sources/CombineSchedulers
  - SDK/Sources/ComposableArchitecture
  - SDK/Sources/ConcurrencyExtras
  - SDK/Sources/CustomDump
  - SDK/Sources/Dependencies
  - SDK/Sources/IdentifiedCollections
  - SDK/Sources/Perception
  - SDK/Sources/SwiftUINavigation
  - SDK/Sources/SwiftUINavigationCore
  - SDK/Sources/XCTestDynamicOverlay

disabled_rules:
  # Don't warn about things we don't mind
  - function_parameter_count
  - large_tuple
  - multiple_closures_with_trailing_closure #awkward with SwiftUI.Button
  - nesting
  - shorthand_operator
  - todo #we use expiring_todo and todo_format instead
  - void_function_in_ternary
  
  # Don't warn about style rules SwiftFormat will correct on pre-commit
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - comment_spacing
  - duplicate_imports
  - empty_parameters
  - implicit_getter
  - leading_whitespace
  - line_length
  - mark
  - no_space_in_method_call
  - opening_brace
  - operator_whitespace
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unused_closure_parameter
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - last_where
  - legacy_multiple
  - legacy_random
  - lower_acl_than_parent
  # - missing_docs
  - multiline_parameters
  - no_extension_access_modifier
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_outlet
  - private_swiftui_state
  - prohibited_super_call
  - reduce_into
  - self_binding
  - sorted_first_last
  - static_operator
  - toggle_bool

file_length:
  warning: 600

function_body_length:
  warning: 100

identifier_name:
  min_length: 2 # For a variable like `id`
  max_length:
    warning: 1000
    error: 1000

generic_type_name:
  max_length:
    warning: 1000
    error: 1000

type_body_length:
  warning: 400
  error: 500

type_name:
  max_length:
    warning: 1000
    error: 1000

cyclomatic_complexity:
  ignores_case_statements: true

expiring_todo:
  date_format: "yyyy-MM-dd"
  date_separator: "-"
  approaching_expiry_threshold: 0
  expired_severity: warning

custom_rules:
  todo_format:
    name: "TODO Format"
    regex: '\/\/ ?TODO:? (?!\[\d{4}-\d{1,2}-\d{1,2}\] \([a-zA-ZÀ-ž_-]+\))'
    message: "Please follow expiring TODO format: `// TODO: [2022-12-25] (responsible_developer_name) Refactor this by Christmas day!`"
    severity: warning
