#!/bin/sh
set -e

BASE_DIR="$(readlink -f $0 | xargs dirname)"
BUILD_DIR="$BASE_DIR/.build"
SCIPIO_GIT_URL=https://github.com/giginet/Scipio.git
SCIPIO_GIT_TAG=0.18.2
SCIPIO_GIT_DIR="$BASE_DIR/.build/scipio"
SCIPIO_BIN="$SCIPIO_GIT_DIR/.build/release/scipio"
SOURCE_DIR="$BASE_DIR/FlatSDK"
DESTINATION_DIR="$BASE_DIR/BinarySDK"
FRAMEWORKS_DIR="$DESTINATION_DIR/XCFrameworks"

message() {
  echo "\n\033[1;32m▶ $1\033[0m\n"
}

message "🔨 Flatten SDK"

(cd "$BASE_DIR/Tools"; swift run flatten)

message "📋 Copy source modules"

cp -R "${SOURCE_DIR}/Sources/UserLingua" "${DESTINATION_DIR}/Sources"
cp -R "${SOURCE_DIR}/Sources/UserLinguaMacros" "${DESTINATION_DIR}/Sources"
cp -R "${SOURCE_DIR}/Sources/UserLinguaExternalMacros" "${DESTINATION_DIR}/Sources"

message "🧹 Prepare build directory"

if [ ! -d "$BUILD_DIR" ]; then
  mkdir -p "$BUILD_DIR"
fi

if [ ! -d "$SCIPIO_GIT_DIR" ]; then
  message "⬇️ Fetch Scipio"
  git clone --depth 1 --branch "$SCIPIO_GIT_TAG" "$SCIPIO_GIT_URL" "$SCIPIO_GIT_DIR"

  message "🏗️ Build Scipio"
  (cd "$SCIPIO_GIT_DIR"; swift build -c release)
fi

message "🗑️  Delete XCFrameworks"
rm -rf "$FRAMEWORKS_DIR"
mkdir "$FRAMEWORKS_DIR"

message "🏗️  Build XCFrameworks"
"$SCIPIO_BIN" create\
  "$SOURCE_DIR"\
  --output "$FRAMEWORKS_DIR"\
  --configuration release\
  --embed-debug-symbols\
  --support-simulators\
  --overwrite\
  --platforms iOS\
  --enable-library-evolution\
  --static

message "🗑️  Delete unnecessary XCFrameworks"
rm -rf "${DESTINATION_DIR}/XCFrameworks/UserLingua.xcframework"
rm -rf "${DESTINATION_DIR}/XCFrameworks/UserLinguaMacros.xcframework"

message "✅ Done"
