// Scoped.swift

/// The init(parent:) is generated by Sourcery
/// by assigning every stored property the value of the
/// identically named property in Parent.
public protocol Scoped {
    associatedtype Parent
}
